name: jiosaavn_api
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_des: ^1.0.0
  http: ^0.13.3

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
